name: Build and publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_extensions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra: ['12.0', '12.0.1', '12.0.2', '12.0.3']

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Java
        uses: actions/setup-java@main
        with:
          java-version: 21
          distribution: temurin

      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Setup Ghidra
        uses: er28-0652/setup-ghidra@master
        with:
          version: ${{ matrix.ghidra }}

      - name: Build GhidraOrbis
        uses: eskatos/gradle-command-action@v2
        with:
          gradle-version: 8.14
          arguments: buildExtension -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }}

      - name: Upload GhidraOrbis Artifact
        uses: actions/upload-artifact@main
        with:
          name: ${{ matrix.ghidra }}
          path: dist/*.zip
          if-no-files-found: error
          compression-level: 0

  push_release:
    if: github.event_name == 'push'
    needs: build_extensions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Download artifacts
        uses: actions/download-artifact@main
        with:
          merge-multiple: true
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create 1.0${{ GITHUB.RUN_NUMBER }} ./*.zip --target ${{ GITHUB.SHA }} -t 1.0${{ GITHUB.RUN_NUMBER }}

